name: platform
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - dav1d=1.2.1
  - freexl=2.0.0
  - gdal=3.10.2
  - geos=3.13.1
  - geotiff=1.7.4
  - giflib=5.2.2
  - icu=75.1
  - json-c=0.18
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal-core=3.10.2
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libheif=1.19.6
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcrypt=4.4.36
  - libxml2=2.13.6
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.7
  - ncurses=6.5
  - numpy=2.2.3
  - openssl=3.4.1
  - pcre2=10.44
  - pip=25.0.1
  - proj=9.5.1
  - python=3.10.16
  - python_abi=3.10
  - rav1e=0.6.6
  - readline=8.2
  - setuptools=75.8.2
  - snappy=1.2.1
  - sqlite=3.49.1
  - svt-av1=3.0.0
  - tk=8.6.13
  - uriparser=0.9.8
  - wheel=0.45.1
  - x265=3.5
  - xerces-c=3.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - attrs==25.1.0
    - certifi==2025.1.31
    - click==8.1.8
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - fiona==1.10.1
    - fonttools==4.56.0
    - future==1.0.0
    - geopandas==1.0.1
    - imageio==2.37.0
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - matplotlib==3.10.1
    - networkx==3.4.2
    - neupy==0.6.5
    - packaging==24.2
    - pandas==2.2.3
    - patsy==1.0.1
    - pillow==11.1.0
    - progressbar2==3.34.3
    - pyogrio==0.10.0
    - pyparsing==3.2.1
    - pyproj==3.7.1
    - python-dateutil==2.9.0.post0
    - python-graphviz==0.5.1
    - python-utils==3.9.1
    - pytz==2025.1
    - scikit-image==0.25.2
    - scipy==1.15.2
    - shapely==2.0.7
    - six==1.17.0
    - statsmodels==0.14.4
    - tableprint==0.7.1
    - theano==1.0.0
    - tifffile==2025.2.18
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - wcwidth==0.2.13
